// <auto-generated />
namespace E_Apartments.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DAapartment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DAapartment));
        
        string IMigrationMetadata.Id
        {
            get { return "202301211559457_DA apartment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
