// <auto-generated />
namespace E_Apartments.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class extendreqchange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(extendreqchange));
        
        string IMigrationMetadata.Id
        {
            get { return "202301171928490_extend req change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
